name: icehomes
main: ru.iceeburr.icehomes.Main
version: 0.0.2
api-version: 1.15
authors: ["iceeburr"]
description: A simple light-weight home plugin designed for Vanilla SMPs
commands:
  sethome:
    description: Set a new home.
    usage: /<command> <homeName>
  home:
    description: Teleport to a home.
    usage: /<command> <homeName>