name: icehomes
main: ru.iceeburr.icehomes.Plugin
version: 0.0.1
api-version: 1.15
authors: ["iceeburr"]
description: A simple ligth-weight homes plugin designed for Vanilla SMPs.
commands:
  register:
    description: Sent a string to the server.
    usage: /<command> <string>
    aliases: [r]